default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: jsl-portal-development

test: &test
  <<: *default
  database: jsl-portal-test

production:
  <<: *default
  database: jsl-portal-production

cucumber:
  <<: *test
